version: '3'
services:
  todoapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: testdb
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: testdb
    volumes:
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql
      - todo-flask-app-volume:/var/lib/mysql
volumes:
  todo-flask-app-volume:
