version: '3'
services:
  todoapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./home/ubuntu/projects/volumes/todo-flask-app:/app/data
volumes:
  todo-flask-app-volume:
